ASSUME CS:CODIGO, DS:DATOS, SS:PILA

;ALMACENAR EN UNA VARIABLE DE MEMORIA (TIPO STRING) LOS CARACTERES INGRESADOS POR TECLADO, MÁXIMO 30 CARACTERES, LUEGO QUE IMPRIMA LA CADENA DE CARACTERES COMPLETA.

;BX Y CX FUNCIONAN COMO UNO SOLO, AMBOS SON EL SUB-INDICE DEL VECTOR.
;(revisar también el archivo que determina el elemento máximo de un vector)

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX
	
	MOV BX, OFFSET VECTOR		;SE ASIGNA A BX LA DIRECCIÓN EN EL DS DEL VECTOR. BX APUNTA A LA DIRECCIÓN DEL DATO DE UN VECTOR, YA SEA PARA ALMACENAR O EXTRAER UN DATO.
	MOV CX, 0					;CX LLEVA EL TAMAÑO DEL VECTOR, INDICA EN QUÉ POSICIÓN ESTÁ EL APUNTADOR BX Y DÓNDE TERMINA EL VECTOR. 
ETIQ2:
	MOV AH, 01H
	INT 21H
	CMP AL, 0DH					;EL PROGRAMA TERMINA CUANDO SE HALLA PRESIONADO LA TECLA ENTER O SE HALLA DIGITADO 30 CARACTERES.
	JE ETIQ1
	MOV [BX], AL				;ALMACENA EL VALOR DE AL EN EL VECTOR EN LA DIRECCIÓN DEL DS QUE APUNTA BX, ES POR ESO QUE BX LLEVA LAS BARRAS. LAS BARRAS INDICAN 'POSICIÓN BX DE MEMORIA' EN EL DS.
	INC BX						;INCREMENTA BX PARA QUE ASÍ PUEDA SEGUIR A LA SIGUIENTE POSICIÓN DEL VECTOR.
	INC CX						;INCREMENTA C PARA QUE LLEVAR EL CONTROL DE LA CANTIDAD DE VALORES INGRESADOS.
	CMP CX, 30					;COMPRUEBA SI EL VECTOR SE HA LLENADO. SI SE HA LLENADO, INMEDIATAMENTE VA A IMPRIMIR Y NO SE INGRESAN MÁS CARACTERES.
	JE ETIQ1
	JMP ETIQ2
ETIQ1:
	CALL SALTOLINEA
	MOV BX, OFFSET VECTOR 		;SE RESETEA BX PARA QUE IMPRIMA LOS DATOS DESDE LA PRIMERA POSICIÓN.
ETIQ3:
	CMP CX, 0					;SE EMPIEZA A DECREMENTAR CX HASTA LLEGAR A CERO, CON EL FIN DE QUE SE IMPRIMA EL TOTAL DE CARACTERES INGRESADOS.
	JE FIN
	MOV DL, [BX]				;SE ASIGNA A DL EL DATO QUE APUNTA BX.
	MOV AH, 02H
	INT 21H
	DEC CX
	INC BX
	JMP ETIQ3
FIN:
	MOV AH,4CH  
	INT 21H

		;SUBRUTINA PARA EL SALTO DE LÍNEA:
			SALTOLINEA PROC
				MOV AH,02H 
				MOV DL,0AH ;SALTO DE LÍNEA
				INT 21H
				MOV AH,02H 
				MOV DL,0DH ;RETORNO DE CARRO
				INT 21H
				RET
			SALTOLINEA ENDP
			
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
VECTOR DB 30 DUP(?)
DATOS ENDS

END