ASSUME CS:CODIGO, DS:DATOS, SS:PILA

;IMPRIMIR POR PANTALLA UN TRIÁNGULO DE N ASTERISCOS, HECHO CON LOOP: (Ver lógica en digrama de flujo en el cuaderno)

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX
	
	MOV BX, N
ETIQ1:
	CMP I, BX
	JA ETIQ2
	MOV CX, I			;IMPRIME I VECES ASTERISCOS.
CICLO:
	CALL IMPRIMIR		
	LOOP CICLO 			;DECREMENTA CX Y SALTA SI CX > 0, CUANDO LLEGA A 0 SALE DEL CICLO.
	CALL SALTOLINEA
	INC I
	JMP ETIQ1
ETIQ2:
	SUB I, 2H			;I LLEGA HASTA EL VALOR DE 6, ASÍ QUE SE LE RESTAN 2 UNIDADES.
ETIQ3:
	CMP I, 0
	JE FIN
	MOV CX, I
CICLO2:
	CALL IMPRIMIR
	LOOP CICLO2
	CALL SALTOLINEA
	DEC I
	JMP ETIQ3
FIN:
	MOV AH,4CH 
	INT 21H
	
	;SUBRUTINA PARA EL SALTO DE LÍNEA:
	SALTOLINEA PROC
		MOV AH,02H 
		MOV DL,0AH ;SALTO DE LÍNEA
		INT 21H
		MOV AH,02H 
		MOV DL,0DH ;RETORNO DE CARRO
		INT 21H
		RET
	SALTOLINEA ENDP
	
	;SUBRUTINA PARA IMPRIMIR:
	IMPRIMIR PROC
		MOV DL, '*'
		MOV AH, 02H
		INT 21H
		RET
	IMPRIMIR ENDP
	
	
		;CONCLUSIONES:
			;LA INSTRUCCIÓN LOOP HACE UN CICLO CON EL NUMERO DE VECES ESPECIFICADO EN EL REGISTRO CX.
			;HACE UN SALTO DE LINEA CADA VEZ QUE SE COMPLETE UN CICLO.
			;SE USA UNA SUBRUTINA PARA EL SALTO DE LINEA Y OTRA PARA IMPRIMIR EL CARACTER.
			
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
N DW 50
I DW 1
DATOS ENDS

END
