ASSUME CS:CODIGO, DS:DATOS, SS:PILA

;IMPRIMIR POR PANTALLA EL TRIÁNGULO DE ASTERISCOS

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX
	
	MOV CL, N
	MOV BL, I
ETIQ4:
	MOV K, 0
	CMP BL, CL
	JA ETIQ1
ETIQ3:
	CMP K, BL
	JE ETIQ2
	MOV DL, AST
	MOV AH, 2H
	INT 21H
	INC K
	JMP ETIQ3
ETIQ2:
	INC BL
	MOV AH,02H 
	MOV DL,0AH ;SALTO DE LÍNEA
	INT 21H
	MOV AH,02H 
	MOV DL,0DH ;RETORNO DE CARRO
	INT 21H
	JMP ETIQ4
ETIQ6: 
	MOV AH,02H 
	MOV DL,0AH ;SALTO DE LÍNEA
	INT 21H
	MOV AH,02H 
	MOV DL,0DH ;RETORNO DE CARRO
	INT 21H
ETIQ1: ;PARA QUE CUANDO SE CUMPLA LA CONDICION I>N NO HAGA UN SALTO DE LINEA.
	MOV K,0
	DEC CL
	CMP CL, 0
	JE ETIQ5
ETIQ7:
	CMP K, CL
	JE ETIQ6
	MOV DL, AST
	MOV AH, 2H
	INT 21H
	INC K
	JMP ETIQ7
ETIQ5:
	MOV AH,4Ch  
	INT 21h         
	
		;CONCLUSIONES:
			;BASÁNDOSE EN EL DIAGRAMA DE FLUJO, LOS SALTOS DE LÍNEA DEBEN DE ESTAR DESPUÉS DE QUE SEA VERDADERA UNA CONDICIÓN O SE COMPLETE 
				;CADA CICLO, ES DECIR, EL SALTO DE LÍNEA VA DESPUES DE LA ETIQUETA A LA QUE SE DIRECCIONA EL SALTO.
			;PRESTAR ATENCIÓN A PARTIR DE LA LÍNEA 30 HASTA LA 52, EN ESPECIAL LAS ETIQUETAS: ETIQ1 Y ETIQ6.
			;CUANDO SE CUMPLE LA CONDICION DE LA ETIQ1 EN LA LÍNEA 14, SALTA A LA LÍNEA 39 SIN HACER EL SALTO DE LINEA.
			
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
AST DB 2AH
N DB 5
I DB 1
K DB 0
DATOS ENDS

END
