ASSUME CS:CODIGO, DS:DATOS, SS:PILA

;CONVERTIR UN NÚMERO EN FORMATO B16 A B10 (mirar apuntes del cuaderno para ver el modo de operación)

;RESTRICCIÓN: EL TOPE MÁXIMO ES 65535 K VECES.

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX
	
	MOV AX, 0FFFCH 	;SE DIGITA EL NÚMERO EN B16 QUE SE CONVERTIRÁ EN B10.
	MOV BX, 0AH		
ET2:				;SE HACE LA DIVISIÓN DEL NÚMERO EN B16 QUE ESTÁ EN AX / A.
	CMP AX, 0H		;VERIFICA SI EL DIVISOR HA LLEGADO A CERO.
	JE ET1
	MOV DX, 0H		;SE HACE USO DE LA OPERACIÓN 1): DX:AX=AX/op EXPLICADA EN EL ARCHIVO DIV.ASM, PARA ESO DX DEBE RELLENARSE DE CEROS.
	DIV BX
	PUSH DX			;SE PONE EL RESIDUO DE LA DIVISIÓN EN LA PILA.
	INC I
	JMP ET2
ET1:
	CMP I, 0H
	JE FIN
	POP DX			;SE SACA DE LA PILA EL RESIDUO QUE SE INGRESO.
	ADD DL, 30H		;SE SUMA 30H AL NÚMERO QUE ESTÁ EN DL PARA HACER LA CONVERSIÓN A ASCII.
	MOV AH, 02H
	INT 21H
	DEC I
	JMP ET1
FIN:
	MOV AH, 4CH
	INT 21H
	
					;MODO DE OPERACIÓN (observar a través del TD):
						;02F8/A=4C  RESIDUO=0, EL RESULTADO SE ALMACENA EN AX, LO QUE NOS BENEFICIA YA QUE ESTE MISMO RESULTADO DEBE DE DIVIDIRSE TAMBIÉN POR A. EL RESIDUO, DX, SE ALMACENA EN LA PILA.
						;4C/A=7 RESIDUO=6
						;7/A RESIDUO=7
						;POR TANTO 02F8=760
						
						
	;EXPLICACIÓN: (http://www.lawebdelprogramador.com/foros/Ensamblador/25978-Necesito-convertir-hexa-a-decimal-en-ensamblador.html)
	
		;IMAGINA QUE TIENES EL NÚMERO 2F8 Y QUIERES SABER CUANTO VALE EN DECIMAL. LO PRIMERO QUE HAY QUE HACER ES DIVIDIRLO POR 10D (O 0AH). EL RESULTADO SERÁ 4CH, Y EL RESTO (QUE TAMBIÉN ES IMPORTANTE) SERÁ 0.
		;ESE 0 SERÁ EL PRIMER DÍGITO DE LA DERECHA DEL NÚMERO EN DECIMAL. SEGUIMOS. TENEMOS EL RESULTADO 4CH, Y REPETIMOS LA OPERACIÓN. AL DIVIDIRLO POR 10D (0AH) OBTENEMOS EL NÚMERO 07H, Y COMO RESTO 6. ESE SERÁ 
		;EL SIGUIENTE DÍGITO EN DECIMAL DEL NÚMERO. Y REPETIMOS. TENEMOS EL 07H, LO DIVIDIMOS POR 0AH, Y OBTENEMOS COMO RESULTADO 0, Y COMO RESTO 7, QUE SERÁ EL SIGUIENTE DÍGITO. POR ÚLTIMO NOS DAMOS CUENTA DE QUE 
		;EL ÚLTIMO RESULTADO OBTENIDO ES 0, A SI ES QUE NO CONTINUAMOS DIVIDIENDO. TOTAL, TENEMOS LOS DÍGITOS 0, 6 Y 7. TENEMOS QUE ESCRIBIRLOS EN ORDEN INVERSO, ES DECIR: 760, JUSTO EL VALOR DE 2F8H EN DECIMAL. 
		;PARA HACERLO EN ENSAMBLADOR, LO MEJOR ES IR DIVIDIENDO Y METIENDO LOS RESTOS DE CADA DIVISIÓN EN LA PILA. CUANDO EL RESULTADO DE LA DIVISIÓN SEA 0, SACAMOS TANTOS DÍGITOS DE LA PILA COMO DIVISIONES HAYAMOS 
		;HECHO, Y LOS VAMOS ESCRIBIENDO. AL USAR LA PILA DAMOS "LA VUELTA" A LOS RESTOS, ES DECIR SACAREMOS EL ÚLTIMO DE LA PILA AL PRIMERO QUE HAYAMOS CALCULADO, POR LO QUE LO ESCRIBIREMOS JUSTO EN EL DÍGITO DE LA 
		;DERECHA COMO NECESITAMOS.
	
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
I DW 0H ;CUENTA LA CANTIDAD DE VECES QUE SE HA INGRESADO UN DATO EN LA PILA, ESTO
		;CON EL FIN DE QUE ESA MISMA CANTIDAD SEA SACADA DE LA PILA.
DATOS ENDS

END
