ASSUME CS:CODIGO, DS:DATOS, SS:PILA

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX
	
	CALL LECTURATECLA
	MOV A, AX			;EN LA VARIABLE A SE GUARDA EL VALOR DEL NÚMERO INGRESADO.
ETIQ2:
	INC B				;CONTADOR QUE VA DE 0 A A PARA SER DIVIDIDO.
	MOV AX, A			;REINICIO EN CADA CICLO.
	MOV DX, 0			;DX SE RELLENA DE CEROS EN CADA CICLO PARA HACER USO DE LA OPERACIÓN 1 DE LA DIVISIÓN.
	CMP B, AX
	JA ETIQ1
	MOV BX, B
	DIV BX
	CMP DX, 0			;SI B MOD A ES IGUAL A CERO, D CUENTA LAS VECES EN QUE ESTO SUCEDE.
	JNE ETIQ2
	INC D				
	JMP ETIQ2
ETIQ1:
	CALL SALTOLINEA
	CMP D, 2			;SI D=2 EL NÚMERO ES PRIMO (revisar lógica de cuándo un número es primo).
	JNE ETIQ3
	MOV AH, 9H
	LEA DX, MENSAJE1
	INT 21H
	JMP FIN
ETIQ3:
	MOV AH, 9H
	LEA DX, MENSAJE2
	INT 21H
FIN:
	MOV AH, 4CH
	INT 21H
	
			;SUBRUTINA PARA EL INGRESO POR TECLADO DE UN NÚMERO DE 4 DÍGITOS:
			LECTURATECLA PROC		;INGRESO DE NÚMEROS POR TECLADO.
				MOV AH, 9H
				LEA DX, MENSAJE 
				INT 21H
			ETQ2:
				MOV AH, 01H			;(revisar archivo LECTEC.ASM)
				INT 21H
				MOV AH, 0H			;PARA QUE QUE NO INTERFIERA EL SERVICIO 01H
				CMP AL, 0DH			;EL PROGRAMA TERMINA CUANDO SE OPRIME LA TECLA ENTER O SE HA LLEGADO AL TOPE DE DÍGITOS INGRESADOS.
				JE ETQ1
				PUSH AX
				INC N				;CUENTA LAS VECES QUE SE HA DIGITADO UN NÚMERO.
				CMP N, 4H			;SE DEFINE EL TOPE DE DÍGITOS QUE SE TIENEN QUE INGRESAR. SE HACE ESTA COMPARACIÓN EN ESTA PARTE PARA QUE CUANDO SE LLEGUE 
				JE ETQ1			;AL TOPE DE INMEDIATO IMPRIMA Y NO SE DIGITE MÁS DIGITOS POR TECLADO.
				JMP ETQ2
			ETQ1:
				CMP N, 1H			;SI N=1 ES PORQUE SE HA INGRESADO UN NÚMERO DE UN DÍGITO (0-9)
				JNE ETQ3
				POP DX
				SUB DL, 30H
				MOV AX, DX			;RESULTADO EN AX.
				JMP SALIR
			ETQ3:
				CMP N, 2H			;SI N=2 ES PORQUE SE HA INGRESADO UN NÚMERO DE DOS DÍGITOS (10-99).
				JNE ETQ4
				POP DX			
				SUB DL, 30H			;PARA CONVERTIR DE ASCII A DECIMAL.
				MOV BX, DX
				POP DX
				SUB DL, 30H
				MOV AX, DX
				MOV CX, J
				MUL CX				;MULTIPLICA POR 10^1 Y EL RESULTADO SE GUARDA EN DX/AX
				ADD AX, BX			;CONVERSIÓN DE HEXADECIMAL A DECIMAL, E IMPRESIÓN POR PANTALLA. (revisar archivo CONV.ASM)
				JMP SALIR
			ETQ4:
				CMP N, 3H			;SI N=3 ES PORQUE SE HAN INGRESADO UN NÚMERO DE TRES DÍGITOS (100-999).
				JNE ETQ7
				POP DX			
				SUB DL, 30H			;PARA CONVERTIR DE ASCII A DECIMAL.
				MOV BX, DX			;EL PRIMER VALOR QUE SE SACA DE LA PILA SE GUARDA EN BX.
				POP DX
				SUB DL, 30H
				MOV AX, DX
				MOV CX, J
				MUL CX
				MOV M, AX			;EL SEGUNDO VALOR QUE SE SACA DE LA PILA SE GUARDA EN M.
				POP DX
				SUB DL, 30H
				MOV AX, DX
				MOV CX, K			;MULTIPLICA POR 10^2 Y EL RESULTADO SE GUARDA EN DX/AX
				MUL CX
				ADD AX, M
				ADD AX, BX			;SE HACE LA OPERACIÓN AX+BX+M.
				JMP SALIR
			ETQ7:
				CMP N, 4H			;SI N=4 ES PORQUE SE HA INGRESADO UN NÚMERO DE CUATRO DÍGITOS (1000-9999)
				JNE SALIR
				POP DX
				SUB DL, 30H
				MOV BX, DX			;EL PRIMER VALOR QUE SE SACA DE LA PILA SE GUARDA EN BX.
				POP DX
				SUB DL, 30H
				MOV AX, DX
				MOV CX, J
				MUL CX
				MOV M, AX			;EL SEGUNDO VALOR QUE SE SACA DE LA PILA SE GUARDA EN M.
				POP DX
				SUB DL, 30H
				MOV AX, DX
				MOV CX, K		
				MUL CX
				MOV O, AX			;EL TERCER VALOR QUE SE SACA DE LA PILA SE GUARDA EN 0.
				POP DX
				SUB DL, 30H
				MOV AX, DX
				MOV CX, P			;MULTIPLICA POR 10^3 Y EL RESULTADO SE GUARDA EN DX/AX.
				MUL CX
				ADD AX, O			;SE HACE LA OPERACIÓN AX+BX+O+M
				ADD AX, M
				ADD AX, BX
				JMP SALIR
			SALIR:
				RET
			LECTURATECLA ENDP

			SALTOLINEA PROC
				MOV AH,02H 
				MOV DL,0AH 			;SALTO DE LÍNEA
				INT 21H
				MOV AH,02H 
				MOV DL,0DH 			;RETORNO DE CARRO
				INT 21H
				RET
			SALTOLINEA ENDP     
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
A DW 0		
B DW 0				;CONTADOR QUE VA DE 0 A A PARA SER DIVIDIDO.
D DW 0				;CUENTA LAS VECES EN QUE A MOD B ES IGUAL A CERO.
;VARIABLES PARA LA UNIÓN DE LOS NÚMEROS.
J DW 10
K DW 100
P DW 1000
;CONTADORES:
N DB 0H				;CUENTA LAS VECES QUE SE HA INGRESADO UN NÚMERO.
I DB 0H				;CONTADOR DE LA SUBRUTINA PARA IMPRIMIR EL RESULTADO EN DECIMAL.
;VARIABLES DONDE SE ALMACENAN RESULTADOS:
M DW 0H				;SE ALMACENA EL VALOR MULTIPLICADO POR 10.
O DW 0H				;SE ALMACENA EL VALOR MULTIPLICADO POR 100.
MENSAJE DB "INGRESE UN NUMERO $"
MENSAJE1 DB "EL NUMERO ES PRIMO $"
MENSAJE2 DB "EL NUMERO NO ES PRIMO $"
DATOS ENDS

END
