ASSUME CS:CODIGO, DS:DATOS, SS:PILA

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX
	
	;IMPRIMIR POR PANTALLA EL ALFABETO EN MAYÚSCULAS: (VER DIAGRAMA DE FLUJO Y APUNTES DEL CUADERNO).
	
ETIQ2:
	MOV AL, A ;1
	CMP AL, Z1 ;2
	JE ETIQ1 ;3
	MOV DL, A ;4 IMPRIME POR PANTALLA.
	MOV AH,2h
	INT 21h
	INC A
	JMP ETIQ2 ;5
	
ETIQ1:	
	MOV AH,4Ch  
	INT 21h  

		;LÓGICA DEL FLUJO DEL CÓDIGO:
		
		;1) SE ALMACENA EN EL REGISTRO AL (8 BITS) EL CARACTER ASCII DE LA LETRA.
		;2) SE COMPARA SI EL VALOR DE LETRA ES IGUAL AL VALOR FINAL: Z+1 ([).
		;3) SI SE CUMPLE LA ANTERIOR CONDICIÓN HARÁ EL SALTO PARA FINALIZAR EL PROGRAMA SIN IMPRIMIR EL CARACTER [.
		;4) SI NO SE CUMPLE LA CONDICIÓN SEGUIRÁ EL FLUJO NORMAL DEL CÓDIGO IMPRIMIENDO POR PANTALLA LA LETRA E INCREMENTANDO 
		;	EL VALOR DE LA MISMA PARA QUE PUEDA ABARCAR LAS DEMÁS LETRAS DEL ALFABETO.
		;5) UNA VEZ HECHO EL PASO4 SE HACE UN SALTO INCONDICIONAL HASTA EL PRINCIPIO DEL PROGRAMA PARA QUE LAS DEMÁS LETRAS PUEDAN IMPRIMIRSE.
		
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
A DB 41H	;CÓDIGO ASCII DE LA LETRA A MAYÚSCULA.
Z1 DB 5BH 	;CÓDIGO ASCII DEL CARACTER Z+1, EL CUAL ES [, ESTO CON EL FIN DE QUE SE PUEDA IMPRIMIR LA LETRA Z CUMPLIENDO EL CONDICIONAL JE. 
DATOS ENDS

END
