ASSUME CS:CODIGO, DS:DATOS, SS:PILA

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX
	
	;IMPRIMIR POR PANTALLA EL ALFABETO EN MAYÚSCULAS: (Ver diagrama de flujo y apuntes del cuaderno).
	;(También se puede hacer con un ciclo LOOP)
	
ETIQ2:
	MOV AL, A 	;1
	CMP AL, Z 	;2
	JA ETIQ1 	;3
	MOV DL, A 	;4 IMPRIME POR PANTALLA.
	MOV AH, 2H
	INT 21H
	INC A
	JMP ETIQ2 	;5
	
ETIQ1:	
	MOV AH,4Ch  
	INT 21h  

		;LÓGICA DEL FLUJO DEL CÓDIGO:
		
		;1) SE ALMACENA EN EL REGISTRO AL (8 BITS) EL CARACTER ASCII DE LA LETRA.
		;2) SE COMPARA SI EL VALOR DE LA LETRA ES IGUAL A Z.
		;3) SI SE CUMPLE LA ANTERIOR CONDICIÓN HARÁ EL SALTO PARA FINALIZAR EL PROGRAMA.
		;4) SI NO SE CUMPLE LA CONDICIÓN SEGUIRÁ EL FLUJO NORMAL DEL CÓDIGO IMPRIMIENDO POR PANTALLA LA LETRA E INCREMENTANDO 
		;	EL VALOR DE LA MISMA PARA QUE PUEDA ABARCAR LAS DEMÁS LETRAS DEL ALFABETO.
		;5) UNA VEZ HECHO EL PASO4 SE HACE UN SALTO INCONDICIONAL HASTA EL PRINCIPIO DEL PROGRAMA PARA QUE LAS DEMÁS LETRAS PUEDAN IMPRIMIRSE.
		
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
A DB 41H	;CÓDIGO ASCII DE LA LETRA A MAYÚSCULA.
Z DB 5AH 	;CÓDIGO ASCII DE LA LETRA Z MAYÚSCULA.
DATOS ENDS

END
