ASSUME CS:CODIGO, DS:DATOS, SS:PILA

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX

	MOV DX, 99			;SE ALMACENA EN DX EL NÚMERO QUE SE DESEA IMPRIMIR EN HEXADECIMAL.
	PUSH DX
	AND DL,0F0H 		;PARA QUE SE TRANSFORME EN HEXADECIMAL
	ROR DL,4H
	CALL IMP_HEX		;SE IMPRIME EL DÍGITO HEXADECIMAL MÁS SIGNIFICATIVO.	
	POP DX 
	AND DL,0FH  		;PARA QUE SE TRANSFORME EN HEXADECIMAL	
	CALL IMP_HEX		;SE IMPRIME EL DÍGITO HEXADECIMAL MENOS SIGNIFICATIVO.	 
FIN:
	MOV AH,4Ch  
	INT 21h  
			;SUBRUTINA QUE IMPRIME UN NÚMERO EN HEXADECIMAL 
			IMP_HEX PROC		
				CMP DL,09H
				JG IMP1
				ADD DL,30H		;EN EL CASO QUE SE DEBA IMPRIMIR UN DÍGITO ENTRE 0 Y 9.
				JMP IMP2
			IMP1:
				ADD DL,37H		;EN EL CASO QUE SE DEBA IMPRIMIR UN DÍGITO ENTRE A Y F.
			IMP2:
				MOV AH,2H
				INT 21H
				RET
			IMP_HEX ENDP     
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT

DATOS ENDS

END
