ASSUME CS:CODIGO, DS:DATOS, SS:PILA

;IMPRIMIR POR PANTALLA LOS CARACTERES INGRESADOS POR TECLADO, IMPRIMIENDO SÓLO EN MAYÚSCULAS LOS CARACTERES QUE SON VOCALES:

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX

ETIQ2:
	MOV AH, 07H	;LECTURA DE UN CARACTER POR TECLADO SIN ECO EN PANTALLA.
	INT 21H
	CMP AL, 0DH	;COMPARA SI LA TECLA INGRESADA ES ENTER, SI LO ES FINALIZA EL PROGRAMA, SI NO LO ES, SIGUE EJECUTANDO EL CÓDIGO.
	JE FIN
	CMP AL, a
	JE ETIQa
	CMP AL, e
	JE ETIQe
	CMP AL, i
	JE ETIQi
	CMP AL, o
	JE ETIQo
	CMP AL, u
	JE ETIQu
	MOV DL, AL
    MOV AH, 2H
	INT 21h
	JMP ETIQ2
ETIQa:
	MOV DL, am
	MOV AH, 2H
	INT 21H
	JMP ETIQ2
ETIQe:
	MOV DL, em
	MOV AH, 2H
	INT 21H
	JMP ETIQ2
ETIQi:
	MOV DL, im
	MOV AH, 2H
	INT 21H
	JMP ETIQ2
ETIQo:
	MOV DL, om
	MOV AH, 2H
	INT 21H
	JMP ETIQ2	
ETIQu:
	MOV DL, um
	MOV AH, 2H
	INT 21H
	JMP ETIQ2
FIN:
	MOV AH,4Ch  
	INT 21h         
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
;VOCALES EN MINÚSCULAS PARA SE COMPARADAS:
a DB 61H
e DB 65H
i DB 69H
o DB 6FH
u DB 75H
;VOCALES EN MAYÚSCULAS PARA SER MOSTRADAS EN PANTALLA:
am DB 41H
em DB 45H
im DB 49H
om DB 4FH
um DB 55H
DATOS ENDS

END
