ASSUME CS:CODIGO, DS:DATOS, SS:PILA

;IMPRIMIR POR PANTALLA LOS CARACTERES INGRESADOS POR TECLADO, IMPRIMIENDO SÓLO EN MAYÚSCULAS LOS CARACTERES QUE SON VOCALES:

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX

ETIQ2:
	MOV AH, 07H ;LECTURA DE UN CARACTER POR TECLADO SIN ECO EN PANTALLA.
	INT 21H
	CMP AL, 0DH ;COMPARA SI LA TECLA INGRESADA ES ENTER, SI LO ES FINALIZA EL PROGRAMA, SI NO LO ES, SIGUE EJECUTANDO EL CÓDIGO.
	JE FIN
	CMP AL, a
	JE ETIQ
	CMP AL, e
	JE ETIQ
	CMP AL, i
	JE ETIQ
	CMP AL, o
	JE ETIQ
	CMP AL, u
	JE ETIQ
	MOV DL, AL
    MOV AH, 2H
	INT 21h
	JMP ETIQ2
ETIQ:
	SUB AL, 20H ;SE RESTA AL CARACTER VOCAL 20H PARA HACER LA CONVERSIÓN DE MINÚSCULAS A MAYÚSCULAS
	MOV DL, AL
	MOV AH, 2H
	INT 21H
	JMP ETIQ2
FIN:
	MOV AH,4Ch  
	INT 21h         
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
;VOCALES EN MINÚSCULAS PARA SE COMPARADAS:
a DB 61H
e DB 65H
i DB 69H
o DB 6FH
u DB 75H
DATOS ENDS

END
