ASSUME CS:CODIGO, DS:DATOS, SS:PILA

;INGRESO POR TECLADO DE UN NÚMERO DE A LO SUMO 5 DÍGITOS, NO MAYOR QUE 65535: (La lógica de este programa está en el cuaderno)
;SE IMPLEMENTARÁ EN FORMA DE SUBRUTINA PARA QUE SEA REUTILIZABLE EN OTROS CÓDIGOS.

;A TENER EN CUENTA:	*EL NÚMERO INGRESADO QUEDARÁ GUARDADO EN EL REGISTRO AX.
;					*EL USO DE LA PILA.
;					*INSTRUCCIÓN LEA.
;					*PONER AH EN CEROS CUANDO SE UTILICE UN SERVICIO.
;					*CONVERSIÓN DE ASCCI A DECIMAL.
;					*EN EL REGISTRO CX SE CARGAN LAS VARIABLES POTENCIAS DE 10.
;					*EL USO DE OTRAS SUBRUTINAS Y SUS RESPECTIVAS VARIABLES EN EL DS.
;					*CASO OMISO AL REGISTRO DX AL HACERSE UNA MULTIPLICACIÓN. 

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX
	
	CALL LECTURA_NUMERO
	CALL IMPRIMIR
	MOV AH, 4CH
	INT 21H
	
			LECTURA_NUMERO PROC
				;BREVE MENSAJE:
				MOV AH, 09H
				LEA DX, MENSAJE1
				INT 21H
				;INGRESO DE LOS DÍGITOS DEL NÚMERO:
			LECTNUM2:
				MOV AH, 01H
				INT 21H
				MOV AH, 0H			;PARA QUE QUE NO INTERFIERA EL SERVICIO 01H EN EL REGISTRO AX.
				CMP AL, 0DH			;EL INGRESO DE DÍGITOS TERMINA CUANDO SE HALLA PRESIONADO LA TECLA ENTER O 
				JE LECTNUM1				;SE HALLA LLEGADO AL TOPE, EL CUAL ES UN NÚMERO DE 5 DÍGITOS.
				PUSH AX
				INC N				;N ES UN CONTADOR QUE LLEVA LA CUENTA DE LOS DÍGITOS QUE SE HAN INGRESADO A 
				CMP N, 5H				;LA PILA, ADEMÁS DETERMINA EL TIPO DE NÚMERO A PARTIR DE SUS DÍGITOS. SI N=5, QUIERE 
				JE LECTNUM1				;DECIR QUE SE HA LLEGADO AL TOPE Y SE HA INGRESADO UN NÚMERO DE 5 DÍGITOS.
				JMP LECTNUM2
				;DETERMINACIÓN DEL NÚMERO INGRESADO A PARTIR DE SUS DÍGITOS:
			LECTNUM1:
				CMP N, 01H 			;PARA UN NÚMERO DE UN DÍGITO.
				JNE LECTNUM3
				POP AX
				SUB AX, 30H			;CONVERSIÓN DE ASCCI A DECIMAL.
				JMP SALIR			;RESULTADO GUARDADO EN AX.
			LECTNUM3:
				CMP N, 02H			;PARA UN NÚMERO DE DOS DÍGITOS.
				JNE LECTNUM4
				POP AX
				SUB AX, 30H
				MOV BX, AX			;BX GUARDA EL DÍGITO DOS.
				POP AX
				SUB AX, 30H
				MOV CX, J
				MUL CX				;MULTIPLICA EL DÍGITO UNO POR 10^1 Y EL RESULTADO SE GUARDA EN DX/AX.
				ADD AX, BX			;SE SUMAN EL DÍGITO UNO CON EL DOS Y EL RESULTADO SE GUARDA EN AX.
				JMP SALIR
			LECTNUM4:
				CMP N, 03H			;PARA UN NÚMERO DE TRES DÍGITOS.
				JNE LECTNUM5
				POP AX
				SUB AX, 30H
				MOV BX, AX			;BX GUARDA EL DÍGITO TRES.
				POP AX
				SUB AX, 30H
				MOV CX, J
				MUL CX				;AX GUARDA EL DÍGITO DOS.	
				ADD AX, BX
				MOV R, AX			;LA SUMA DEL DÍGITO DOS CON EL TRES SE GUARDA EN R.
				POP AX
				SUB AX, 30H
				MOV CX, K
				MUL CX				;MULTIPLICA EL DÍGITO UNO POR 10^2 Y EL RESULTADO SE GUARDA EN DX/AX.
				ADD AX, R			;AX = AX+(R+BX).
				JMP SALIR			;SE SUMAN LOS TRES DÍGITOS Y EL RESULTADO SE GUARDA EN AX.
			LECTNUM5:
				CMP N, 04H			;PARA UN NÚMERO DE CUATRO DÍGITOS.
				JNE LECTNUM6
				POP AX
				SUB AX, 30H
				MOV BX, AX			;BX GUARDA EL DÍGITO TRES.
				POP AX
				SUB AX, 30H
				MOV CX, J
				MUL CX				;AX GUARDA EL DÍGITO DOS.	
				ADD AX, BX
				MOV R, AX			;LA SUMA DEL DÍGITO DOS CON EL TRES SE GUARDA EN R.
				POP AX
				SUB AX, 30H
				MOV CX, K
				MUL CX				
				ADD AX, R
				MOV S, AX			;LA SUMA DEL DÍGITO TRES, DOS Y UNO SE GUARDA EN S.
				POP AX
				SUB AX, 30H
				MOV CX, P
				MUL CX				;MULTIPLICA EL DÍGITO UNO POR 10^3 Y EL RESULTADO SE GUARDA EN DX/AX.
				ADD AX, S 			;AX = AX+(S+(R+BX)).
				JMP SALIR			;SE SUMAN LOS CUATRO DÍGITOS Y EL RESULTADO SE GUARDA EN AX.
			LECTNUM6:
				CMP N, 05H			;PARA UN NÚMERO DE CINCO DÍGITOS.
				JNE SALIR
				POP AX
				SUB AX, 30H
				MOV BX, AX			;BX GUARDA EL DÍGITO TRES.
				POP AX
				SUB AX, 30H
				MOV CX, J
				MUL CX				;AX GUARDA EL DÍGITO DOS.	
				ADD AX, BX
				MOV R, AX			;LA SUMA DEL DÍGITO DOS CON EL TRES SE GUARDA EN R.
				POP AX
				SUB AX, 30H
				MOV CX, K
				MUL CX				
				ADD AX, R
				MOV S, AX			;LA SUMA DEL DÍGITO TRES, DOS Y UNO SE GUARDA EN S.
				POP AX
				SUB AX, 30H
				MOV CX, P
				MUL CX
				ADD AX, S
				MOV T, AX			;LA SUMA DEL DÍGITO CUATRO, TRES, DOS Y UNO SE GUARDA EN T.
				POP AX
				SUB AX, 30H
				MOV CX, O
				MUL CX				;MULTIPLICA EL DÍGITO UNO POR 10^4 Y EL RESULTADO SE GUARDA EN DX/AX.
				ADD AX, T			;AX = AX+(T+(S+(R+BX))).
				JMP SALIR			;SE SUMAN LOS CUATRO DÍGITOS Y EL RESULTADO SE GUARDA EN AX.
			SALIR:
				RET
			LECTURA_NUMERO ENDP
	
			;SUBRUTINA PARA EL SALTO DE LÍNEA:
			SALTOLINEA PROC
				MOV AH,02H 
				MOV DL,0AH 			;SALTO DE LÍNEA
				INT 21H
				MOV AH,02H 
				MOV DL,0DH 			;RETORNO DE CARRO
				INT 21H
				RET
			SALTOLINEA ENDP
			
			;SUBRUTINA PARA IMPRIMIR EL RESULTADO:
			IMPRIMIR PROC
				MOV BX, 0AH		
			ET2:					;SE HACE LA DIVISIÓN DEL NÚMERO EN B16 QUE ESTÁ EN AX / A.
				CMP AX, 0H			;COMPRUEBA SI EL DIVISOR HA LLEGADO A CERO.
				JE ET3
				MOV DX, 0H			;SE HACE USO DE LA OPERACIÓN 1) EXPLICADA EN EL ARCHIVO DIV.ASM, PARA ESO DX DEBE RELLENARSE DE CEROS EN CADA CICLO.
				DIV BX
				PUSH DX				;SE PONE EL RESIDUO DE LA DIVISIÓN EN LA PILA.
				INC I
				JMP ET2
			ET3:
				CALL SALTOLINEA		
				MOV AH, 09H
				LEA DX, MENSAJE2	;MENSAJE DE SALIDA
				INT 21H
			ET1:
				CMP I, 0H
				JE FINIMPRIMIR
				POP DX				;SE SACA DE LA PILA EL RESIDUO QUE SE INGRESO.
				ADD DL, 30H			;SE SUMA 30H AL NÚMERO QUE ESTÁ EN DL PARA HACER LA CONVERSIÓN A ASCII.
				MOV AH, 02H
				INT 21H
				DEC I
				JMP ET1
			FINIMPRIMIR:
				RET
			IMPRIMIR ENDP
			
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
;POTENCIAS DE 10:
J DW 10
K DW 100
P DW 1000
O DW 10000
;CONTADORES DEL PROGRAMA:
N DB 0H								;DETERMINA EL TIPO DE NÚMERO A PARTIR DE SUS DÍGITOS.
I DW 0H								;CONTADOR DE LA SUBRUTINA IMPRIMIR_DECIMAL.
;VARIABLES QUE GUARDAN VALORES:
R DW 0H
S DW 0H
T DW 0H
;MENSAJES:
MENSAJE1 DB "INGRESE NUMERO: $"
MENSAJE2 DB "EL NUMERO INGRESADO ES: $"
DATOS ENDS

END
