ASSUME CS:CODIGO, DS:DATOS, SS:PILA

;LECTURA DE UN GRUPO DE NÚMEROS INGRESADOS POR TECLADO POR TECLADO.

;RESTRICCIÓN: TENER EN CUENTA QUE NO SE PODRÁ INGRESAR NÚMEROS DE MÁS DE 4 DÍGITOS PORQUE SE PASARÍA DEL TOPE 2^16.

;NOTA: PARA REALIZAR OPERACIONES ARITMÉTICAS SE LE DEBE DE RESTAR 30H AL DIGITO INGRESADO (CONVERTIR DE ASCII A DECIMAL).

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX
	
	MOV AH, 9H
	LEA DX, MENSAJE 
	INT 21H
ETIQ2:
	MOV AH, 01H
	INT 21H
	MOV AH, 0H		;PARA QUE QUE NO INTERFIERA EL SERVICIO 01H
	CMP AL, 0DH		;EL PROGRAMA TERMINA CUANDO SE OPRIME LA TECLA ENTER O SE HA LLEGADO AL TOPE DE DÍGITOS INGRESADOS.
	JE ETIQ1
	PUSH AX
	INC N			;CUENTA LAS VECES QUE SE HA DIGITADO UN NÚMERO.
	CMP N, 4H		;SE DEFINE EL TOPE DE DÍGITOS QUE SE TIENEN QUE INGRESAR. SE HACE ESTA COMPARACIÓN EN ESTA PARTE PARA QUE CUANDO SE LLEGUE 
	JE ETIQ1			;AL TOPE DE INMEDIATO IMPRIMA Y NO SE DIGITE MÁS DIGITOS POR TECLADO.
	JMP ETIQ2
ETIQ1:
	CALL SALTOLINEA
	CMP N, 1H		;SI N=1 ES PORQUE SE HA INGRESADO UN NÚMERO DE UN DÍGITO (0-9)
	JNE ETIQ3
	POP DX
	MOV AH, 02H
	INT 21H
	JMP FIN
ETIQ3:
	CMP N, 2H		;SI N=2 ES PORQUE SE HA INGRESADO UN NÚMERO DE DOS DÍGITOS (10-99).
	JNE ETIQ4
	POP DX			
	SUB DL, 30H		;PARA CONVERTIR DE ASCII A DECIMAL.
	MOV BX, DX
	POP DX
	SUB DL, 30H
	MOV AX, DX
	MOV CX, J		;MULTIPLICA POR 10^1 Y EL RESULTADO SE GUARDA EN DX/AX
	MUL CX			
	ADD AX, BX		;CONVERSIÓN DE HEXADECIMAL A DECIMAL, E IMPRESIÓN POR PANTALLA. (revisar archivo CONV.ASM)
	CALL IMPRIMIR
ETIQ4:
	CMP N, 3H		;SI N=3 ES PORQUE SE HAN INGRESADO UN NÚMERO DE TRES DÍGITOS (100-999).
	JNE ETIQ5
	POP DX			
	SUB DL, 30H		;PARA CONVERTIR DE ASCII A DECIMAL.
	MOV BX, DX		;EL PRIMER VALOR QUE SE SACA DE LA PILA SE GUARDA EN BX.
	POP DX
	SUB DL, 30H
	MOV AX, DX
	MOV CX, J
	MUL CX
	MOV M, AX		;EL SEGUNDO VALOR QUE SE SACA DE LA PILA SE GUARDA EN M.
	POP DX
	SUB DL, 30H
	MOV AX, DX
	MOV CX, K		;MULTIPLICA POR 10^2 Y EL RESULTADO SE GUARDA EN DX/AX.
	MUL CX
	ADD AX, M
	ADD AX, BX		;SE HACE LA OPERACIÓN AX+BX+M.
	CALL IMPRIMIR
ETIQ5:
	CMP N, 4H		;SI N=4 ES PORQUE SE HA INGRESADO UN NÚMERO DE CUATRO DÍGITOS (1000-9999)
	JNE FIN
	POP DX
	SUB DL, 30H
	MOV BX, DX		;EL PRIMER VALOR QUE SE SACA DE LA PILA SE GUARDA EN BX.
	POP DX
	SUB DL, 30H
	MOV AX, DX
	MOV CX, J
	MUL CX
	MOV M, AX		;EL SEGUNDO VALOR QUE SE SACA DE LA PILA SE GUARDA EN M.
	POP DX
	SUB DL, 30H
	MOV AX, DX
	MOV CX, K		
	MUL CX
	MOV O, AX		;EL TERCER VALOR QUE SE SACA DE LA PILA SE GUARDA EN 0.
	POP DX
	SUB DL, 30H
	MOV AX, DX
	MOV CX, P		;MULTIPLICA POR 10^3 Y EL RESULTADO SE GUARDA EN DX/AX.
	MUL CX
	ADD AX, O		;SE HACE LA OPERACIÓN AX+BX+O+M
	ADD AX, M
	ADD AX, BX
	CALL IMPRIMIR
FIN:
	MOV AH, 4CH
	INT 21H
	
		;SUBRUTINA PARA EL SALTO DE LÍNEA:
			SALTOLINEA PROC
				MOV AH,02H 
				MOV DL,0AH ;SALTO DE LÍNEA
				INT 21H
				MOV AH,02H 
				MOV DL,0DH ;RETORNO DE CARRO
				INT 21H
				RET
			SALTOLINEA ENDP
		
		;SUBRUTINA PARA IMPRIMIR EL RESULTADO EN DECIMAL:
			IMPRIMIR PROC
					MOV BX, 0AH		
				ET2:				
					CMP AX, 0H		
					JE ET1
					MOV DX, 0H		
					DIV BX
					PUSH DX			
					INC I
					JMP ET2
				ET1:
					CMP I, 0H
					JE FIN
					POP DX			
					ADD DL, 30H		
					MOV AH, 02H
					INT 21H
					DEC I
					JMP ET1
					RET
			IMPRIMIR ENDP
	
		;CÓMO UNIR NÚMEROS, ES DECIR, QUE SE INGRESE EL 125 Y LO LEA TODO JUNTO Y NO COMO 1, 2, 5:
		
			;PARA ESTE PROCESO SE APLICA LA DEFINICIÓN DE UNIDAD, DECENA Y CENTENA. UNA UNIDAD ES 10^0, UNA DECENA ES 10^1, UNA DECENA ES 10^2 Y ASÍ
			;SUCESIVAMENTE. EN EL CÓDIGO SE OBSERVA LO DEFINIDO. SI SE INGRESA EL NUMERO 12, SE MULTIPLICA 1*10^1 Y LUEGO SE SUMA CON 2*10^0. 
			
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
;VARIABLES PARA LA UNIÓN DE LOS NÚMEROS.
J DW 10
K DW 100
P DW 1000
;CONTADORES:
N DB 0H				;CUENTA LAS VECES QUE SE HA INGRESADO UN NÚMERO.
I DB 0H				;CONTADOR DE LA SUBRUTINA PARA IMPRIMIR EL RESULTADO EN DECIMAL.
;VARIABLES DONDE SE ALMACENAN RESULTADOS:
M DW 0H				;SE ALMACENA EL VALOR MULTIPLICADO POR 10.
O DW 0H				;SE ALMACENA EL VALOR MULTIPLICADO POR 100.
Q DW 0H
MENSAJE DB "INGRESE VALOR: $"
DATOS ENDS

END
