ASSUME CS:CODIGO, DS:DATOS, SS:PILA

;LISTAR LOS NÚMEROS PRIMOS QUE ESTÁN ENTRE 0 Y N, N ES UN VALOR QUE SE INGRESA POR TECLADO (La lógica de este programa está en el cuaderno):
;UN NÚMERO ES PRIMO CUANDO ES DIVISIBLE POR SÍ MISMO Y LA UNIDAD.

;A TENER EN CUENTA:	*COMO SE HACE USO DE LA PILA LA LISTA DE NÚMEROS SALE EN ORDEN INVERSO.
;					*IMPORTANTE ANALIZAR EL DIAGRAMA DE FLUJO QUE ESTÁ EN EL CUADERNO.
;					*TENER EN CUENTA QUE NO SE PUEDE HACER CMP MEM, MEM.
;					*RELLENAR DE CEROS EL REGISTRO DX PARA PODER HACER LA OPERACIÓN AX=DX:AX/OP.
;					*EL "ESPACIO" SE HACE CON EL 20H ASCII.
;					*EL USO DE OTRAS SUBRUTINAS Y SUS RESPECTIVAS VARIABLES EN EL DS.
;			(analizar diagrama de flujo)
;			PARA EVITAR UN SALTO REDUNDANTE EN: B MOD D = 0 (FALSO) Y EN: E=2 (FALSO) LO IDEAL ES PONER EL INCREMENTADOR
;			B++ Y D++ ANTES DE LA DECISIÓN, LÍNEAS 14 Y 19 RESPECTIVAMENTE.

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX
	
	CALL LECTURA_NUMERO
	MOV A, AX			;N=A.
ETIQ4:
	MOV D, 0			;REINICIO DE D Y E.
	MOV E, 0
	INC B				;NÚMEROS COMPRENDIDOS ENTRE 0 Y N
	MOV CX, B			;PORQUE CMP A, B NO SE PUEDE HACER.
	CMP CX, A
	JA ETIQ1
ETIQ3:
	INC D				
	CMP D, CX 
	JA ETIQ2
	;B MOD D = 0
	MOV AX, CX
	MOV DX, 0			;SE HACE USO DE LA OPERACIÓN AX=DX:AX/OP, PARA ESO DX DEBE RELLENARSE DE CEROS.
	MOV BX, D
	DIV BX
	CMP DX, 0
	JNE ETIQ3
	INC E				;CONTADOR QUE LLEVA LAS VECES EN QUE EL RESTO DE DOS NÚMEROS ES CERO. 
	JMP ETIQ3
ETIQ2:
	CMP E, 2
	JNE ETIQ4
	PUSH CX
	INC F				;CONTADOR QUE LLEVA LAS VECES EN QUE UN NÚMERO ES INGRESADO A LA PILA, TAL NÚMERO DEBE DE SER PRIMO.
	JMP ETIQ4
ETIQ1:
	CALL SALTOLINEA
ETIQ5:
	CMP F, 0
	JE FIN				;EL PROGRAMA TERMINA CUANDO SEA SACADO DE LA PILA F NÚMEROS.
	POP AX
	CALL IMPRIMIR_DECIMAL
	MOV AH, 02H
	MOV DL, 20H			;IMPRIME "ESPACIO"
	INT 21H
	DEC F
	JMP ETIQ5
FIN:
	MOV AH, 4CH
	INT 21H
	
			;SUBRUTINA PARA EL INGRESO POR TECLADO DE UN NÚMERO DE 5 DÍGITOS:
			LECTURA_NUMERO PROC
				;BREVE MENSAJE:
				MOV AH, 09H
				LEA DX, MENSAJE1
				INT 21H
				;INGRESO DE LOS DÍGITOS DEL NÚMERO:
			LECTNUM2:
				MOV AH, 01H
				INT 21H
				MOV AH, 0H			;PARA QUE QUE NO INTERFIERA EL SERVICIO 01H EN EL REGISTRO AX.
				CMP AL, 0DH			;EL INGRESO DE DÍGITOS TERMINA CUANDO SE HALLA PRESIONADO LA TECLA ENTER O 
				JE LECTNUM1				;SE HALLA LLEGADO AL TOPE, EL CUAL ES UN NÚMERO DE 5 DÍGITOS.
				PUSH AX
				INC N				;N ES UN CONTADOR QUE LLEVA LA CUENTA DE LOS DÍGITOS QUE SE HAN INGRESADO A 
				CMP N, 5H				;LA PILA, ADEMÁS DETERMINA EL TIPO DE NÚMERO A PARTIR DE SUS DÍGITOS. SI N=5, QUIERE 
				JE LECTNUM1				;DECIR QUE SE HA LLEGADO AL TOPE Y SE HA INGRESADO UN NÚMERO DE 5 DÍGITOS.
				JMP LECTNUM2
				;DETERMINACIÓN DEL NÚMERO INGRESADO A PARTIR DE SUS DÍGITOS:
			LECTNUM1:
				CMP N, 01H 			;PARA UN NÚMERO DE UN DÍGITO.
				JNE LECTNUM3
				POP AX
				SUB AX, 30H			;CONVERSIÓN DE ASCCI A DECIMAL.
				JMP SALIR			;RESULTADO GUARDADO EN AX.
			LECTNUM3:
				CMP N, 02H			;PARA UN NÚMERO DE DOS DÍGITOS.
				JNE LECTNUM4
				POP AX
				SUB AX, 30H
				MOV BX, AX			;BX GUARDA EL DÍGITO DOS.
				POP AX
				SUB AX, 30H
				MOV CX, J
				MUL CX				;MULTIPLICA EL DÍGITO UNO POR 10^1 Y EL RESULTADO SE GUARDA EN DX/AX.
				ADD AX, BX			;SE SUMAN EL DÍGITO UNO CON EL DOS Y EL RESULTADO SE GUARDA EN AX.
				JMP SALIR
			LECTNUM4:
				CMP N, 03H			;PARA UN NÚMERO DE TRES DÍGITOS.
				JNE LECTNUM5
				POP AX
				SUB AX, 30H
				MOV BX, AX			;BX GUARDA EL DÍGITO TRES.
				POP AX
				SUB AX, 30H
				MOV CX, J
				MUL CX				;AX GUARDA EL DÍGITO DOS.	
				ADD AX, BX
				MOV R, AX			;LA SUMA DEL DÍGITO DOS CON EL TRES SE GUARDA EN R.
				POP AX
				SUB AX, 30H
				MOV CX, K
				MUL CX				;MULTIPLICA EL DÍGITO UNO POR 10^2 Y EL RESULTADO SE GUARDA EN DX/AX.
				ADD AX, R			;AX = AX+(R+BX).
				JMP SALIR			;SE SUMAN LOS TRES DÍGITOS Y EL RESULTADO SE GUARDA EN AX.
			LECTNUM5:
				CMP N, 04H			;PARA UN NÚMERO DE CUATRO DÍGITOS.
				JNE LECTNUM6
				POP AX
				SUB AX, 30H
				MOV BX, AX			;BX GUARDA EL DÍGITO TRES.
				POP AX
				SUB AX, 30H
				MOV CX, J
				MUL CX				;AX GUARDA EL DÍGITO DOS.	
				ADD AX, BX
				MOV R, AX			;LA SUMA DEL DÍGITO DOS CON EL TRES SE GUARDA EN R.
				POP AX
				SUB AX, 30H
				MOV CX, K
				MUL CX				
				ADD AX, R
				MOV S, AX			;LA SUMA DEL DÍGITO TRES, DOS Y UNO SE GUARDA EN S.
				POP AX
				SUB AX, 30H
				MOV CX, P
				MUL CX				;MULTIPLICA EL DÍGITO UNO POR 10^3 Y EL RESULTADO SE GUARDA EN DX/AX.
				ADD AX, S 			;AX = AX+(S+(R+BX)).
				JMP SALIR			;SE SUMAN LOS CUATRO DÍGITOS Y EL RESULTADO SE GUARDA EN AX.
			LECTNUM6:
				CMP N, 05H			;PARA UN NÚMERO DE CINCO DÍGITOS.
				JNE SALIR
				POP AX
				SUB AX, 30H
				MOV BX, AX			;BX GUARDA EL DÍGITO TRES.
				POP AX
				SUB AX, 30H
				MOV CX, J
				MUL CX				;AX GUARDA EL DÍGITO DOS.	
				ADD AX, BX
				MOV R, AX			;LA SUMA DEL DÍGITO DOS CON EL TRES SE GUARDA EN R.
				POP AX
				SUB AX, 30H
				MOV CX, K
				MUL CX				
				ADD AX, R
				MOV S, AX			;LA SUMA DEL DÍGITO TRES, DOS Y UNO SE GUARDA EN S.
				POP AX
				SUB AX, 30H
				MOV CX, P
				MUL CX
				ADD AX, S
				MOV T, AX			;LA SUMA DEL DÍGITO CUATRO, TRES, DOS Y UNO SE GUARDA EN T.
				POP AX
				SUB AX, 30H
				MOV CX, O
				MUL CX				;MULTIPLICA EL DÍGITO UNO POR 10^4 Y EL RESULTADO SE GUARDA EN DX/AX.
				ADD AX, T			;AX = AX+(T+(S+(R+BX))).
				JMP SALIR			;SE SUMAN LOS CUATRO DÍGITOS Y EL RESULTADO SE GUARDA EN AX.
			SALIR:
				RET
			LECTURA_NUMERO ENDP 
	
			IMPRIMIR_DECIMAL PROC
				MOV BX, 0AH			;EN BX SE ALMACENA EL DIVISOR A.
			IMPDECI2:
				CMP AX, 0H			;COMPRUEBA SI EL DIVISOR HA LLEGADO A CERO, SI ES CERO ENTONCES SALTA A IMPRIMIR.
				JE IMPDECI1
				MOV DX, 0H			;SE HACE USO DE LA OPERACIÓN AX=DX:AX/OP, PARA ESO DX DEBE RELLENARSE DE CEROS.
				DIV BX
				PUSH DX				;SE PONE EL RESIDUO DE LA DIVISIÓN EN LA PILA.
				INC I
				JMP IMPDECI2
			IMPDECI1:
				CMP I, 0H
				JE FIN_IMPRIMIR
				POP DX				;SE SACA DE LA PILA EL RESIDUO QUE SE INGRESÓ.
				ADD DX, 30H			;SE SUMA 30H PARA HACER LA CONVERSIÓN DE DECIMAL A ASCII.
				MOV AH, 02H
				INT 21H
				DEC I
				JMP IMPDECI1
			FIN_IMPRIMIR:
				RET
			IMPRIMIR_DECIMAL ENDP
			
			SALTOLINEA PROC
				MOV AH,02H 
				MOV DL,0AH 			;SALTO DE LÍNEA
				INT 21H
				MOV AH,02H 
				MOV DL,0DH 			;RETORNO DE CARRO
				INT 21H
				RET
			SALTOLINEA ENDP
			
			;NOTA: 
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
;POTENCIAS DE 10:
J DW 10
K DW 100
P DW 1000
O DW 10000
;CONTADORES DEL PROGRAMA:
N DB 0H					;DETERMINA EL TIPO DE NÚMERO A PARTIR DE SUS DÍGITOS.
I DW 0H					;CONTADOR DE LA SUBRUTINA IMPRIMIR_DECIMAL.
;VARIABLES Y CONTADORES DECLARADOS EN EL DIAGRAMA DE FLUJO:
A DW 0H					
B DW 0H
D DW 0H
E DW 0H					;CONTADOR QUE LLEVA LAS VECES EN QUE EL RESTO DE DOS NÚMEROS ES CERO.
F DW 0H					;CONTADOR QUE LLEVA LAS VECES EN QUE UN NÚMERO ES INGRESADO A LA PILA, TAL NÚMERO DEBE DE SER PRIMO.
;VARIABLES QUE GUARDAN VALORES:
R DW 0H
S DW 0H
T DW 0H
;MENSAJES:
MENSAJE1 DB "INGRESE NUMERO: $"
DATOS ENDS

END
