ASSUME CS:CODIGO, DS:DATOS, SS:PILA

;LISTAR LOS NÚMEROS PRIMOS QUE ESTÁN ENTRE 0 Y N, N ES UN VALOR QUE SE INGRESA POR TECLADO:
;UN NÚMERO ES PRIMO CUANDO ES DIVISIBLE POR SÍ MISMO Y LA UNIDAD (analizar el diagrama de flujo del cuaderno)
;COMO SE HACE USO DE LA PILA LA LISTA DE NÚMEROS SALE EN ORDEN INVERSO. 

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX
	
	CALL LECTURATECLA
	MOV A, AX
ETIQ4:
	MOV D, 0
	MOV E, 0
	INC B				;NÚMEROS COMPRENDIDOS ENTRE 0 Y N
	MOV CX, B			;PORQUE CMP A, B NO SE PUEDE HACER.
	CMP CX, A
	JA ETIQ1
ETIQ3:
	INC D				
	CMP D, CX 
	JA ETIQ2
	;B MOD D = 0
	MOV AX, CX
	MOV DX, 0			;DX SE RELLENA DE CEROS PARA PODER HACER LA OPERACIÓN 1 DE LA DIVISIÓN.
	MOV BX, D
	DIV BX
	CMP DX, 0
	JNE ETIQ3
	INC E				;CONTADOR QUE LLEVA LAS VECES EN QUE EL RESTO DE DOS NÚMEROS ES CERO. 
	JMP ETIQ3
ETIQ2:
	CMP E, 2
	JNE ETIQ4
	PUSH CX
	INC F				;CONTADOR QUE LLEVA LAS VECES EN QUE UN NÚMERO ES INGRESADO A LA PILA, TAL NÚMERO DEBE DE SER PRIMO.
	JMP ETIQ4
ETIQ1:
	CALL SALTOLINEA
ETIQ5:
	CMP F, 0
	JE FIN				;EL PROGRAMA TERMINA CUANDO SEA SACADO DE LA PILA F NÚMEROS.
	POP AX
	CALL IMPRIMIR
	MOV AH, 02H
	MOV DL, 20H			;IMPRIME "ESPACIO"
	INT 21H
	DEC F
	JMP ETIQ5
FIN:
	MOV AH, 4CH
	INT 21H
	
			;SUBRUTINA PARA EL INGRESO POR TECLADO DE UN NÚMERO DE 4 DÍGITOS:
			LECTURATECLA PROC		;INGRESO DE NÚMEROS POR TECLADO.
				MOV AH, 9H
				LEA DX, MENSAJE 
				INT 21H
			ETQ2:
				MOV AH, 01H			;(revisar archivo LECTEC.ASM)
				INT 21H
				MOV AH, 0H			;PARA QUE QUE NO INTERFIERA EL SERVICIO 01H
				CMP AL, 0DH			;EL PROGRAMA TERMINA CUANDO SE OPRIME LA TECLA ENTER O SE HA LLEGADO AL TOPE DE DÍGITOS INGRESADOS.
				JE ETQ1
				PUSH AX
				INC N				;CUENTA LAS VECES QUE SE HA DIGITADO UN NÚMERO.
				CMP N, 4H			;SE DEFINE EL TOPE DE DÍGITOS QUE SE TIENEN QUE INGRESAR. SE HACE ESTA COMPARACIÓN EN ESTA PARTE PARA QUE CUANDO SE LLEGUE 
				JE ETQ1			;AL TOPE DE INMEDIATO IMPRIMA Y NO SE DIGITE MÁS DIGITOS POR TECLADO.
				JMP ETQ2
			ETQ1:
				CMP N, 1H			;SI N=1 ES PORQUE SE HA INGRESADO UN NÚMERO DE UN DÍGITO (0-9)
				JNE ETQ3
				POP DX
				SUB DL, 30H
				MOV AX, DX			;RESULTADO EN AX.
				JMP SALIR
			ETQ3:
				CMP N, 2H			;SI N=2 ES PORQUE SE HA INGRESADO UN NÚMERO DE DOS DÍGITOS (10-99).
				JNE ETQ4
				POP DX			
				SUB DL, 30H			;PARA CONVERTIR DE ASCII A DECIMAL.
				MOV BX, DX
				POP DX
				SUB DL, 30H
				MOV AX, DX
				MOV CX, J
				MUL CX				;MULTIPLICA POR 10^1 Y EL RESULTADO SE GUARDA EN DX/AX
				ADD AX, BX			;CONVERSIÓN DE HEXADECIMAL A DECIMAL, E IMPRESIÓN POR PANTALLA. (revisar archivo CONV.ASM)
				JMP SALIR
			ETQ4:
				CMP N, 3H			;SI N=3 ES PORQUE SE HAN INGRESADO UN NÚMERO DE TRES DÍGITOS (100-999).
				JNE ETQ7
				POP DX			
				SUB DL, 30H			;PARA CONVERTIR DE ASCII A DECIMAL.
				MOV BX, DX			;EL PRIMER VALOR QUE SE SACA DE LA PILA SE GUARDA EN BX.
				POP DX
				SUB DL, 30H
				MOV AX, DX
				MOV CX, J
				MUL CX
				MOV M, AX			;EL SEGUNDO VALOR QUE SE SACA DE LA PILA SE GUARDA EN M.
				POP DX
				SUB DL, 30H
				MOV AX, DX
				MOV CX, K			;MULTIPLICA POR 10^2 Y EL RESULTADO SE GUARDA EN DX/AX
				MUL CX
				ADD AX, M
				ADD AX, BX			;SE HACE LA OPERACIÓN AX+BX+M.
				JMP SALIR
			ETQ7:
				CMP N, 4H			;SI N=4 ES PORQUE SE HA INGRESADO UN NÚMERO DE CUATRO DÍGITOS (1000-9999)
				JNE SALIR
				POP DX
				SUB DL, 30H
				MOV BX, DX			;EL PRIMER VALOR QUE SE SACA DE LA PILA SE GUARDA EN BX.
				POP DX
				SUB DL, 30H
				MOV AX, DX
				MOV CX, J
				MUL CX
				MOV M, AX			;EL SEGUNDO VALOR QUE SE SACA DE LA PILA SE GUARDA EN M.
				POP DX
				SUB DL, 30H
				MOV AX, DX
				MOV CX, K		
				MUL CX
				MOV O, AX			;EL TERCER VALOR QUE SE SACA DE LA PILA SE GUARDA EN 0.
				POP DX
				SUB DL, 30H
				MOV AX, DX
				MOV CX, P			;MULTIPLICA POR 10^3 Y EL RESULTADO SE GUARDA EN DX/AX.
				MUL CX
				ADD AX, O			;SE HACE LA OPERACIÓN AX+BX+O+M
				ADD AX, M
				ADD AX, BX
				JMP SALIR
			SALIR:
				RET
			LECTURATECLA ENDP    
	
			IMPRIMIR PROC
				MOV BX, 0AH		
			ET2:					;SE HACE LA DIVISIÓN DEL NÚMERO EN B16 QUE ESTÁ EN AX / A.
				CMP AX, 0H			;COMPRUEBA SI EL DIVISOR HA LLEGADO A CERO.
				JE ET1
				MOV DX, 0H			;SE HACE USO DE LA OPERACIÓN 1) EXPLICADA EN EL ARCHIVO DIV.ASM, PARA ESO DX DEBE RELLENARSE DE CEROS EN CADA CICLO.
				DIV BX
				PUSH DX				;SE PONE EL RESIDUO DE LA DIVISIÓN EN LA PILA.
				INC I
				JMP ET2
			ET1:
				CMP I, 0H
				JE FINIMPRIMIR
				POP DX				;SE SACA DE LA PILA EL RESIDUO QUE SE INGRESO.
				ADD DL, 30H			;SE SUMA 30H AL NÚMERO QUE ESTÁ EN DL PARA HACER LA CONVERSIÓN A ASCII.
				MOV AH, 02H
				INT 21H
				DEC I
				JMP ET1
			FINIMPRIMIR:
				RET
			IMPRIMIR ENDP
			
			SALTOLINEA PROC
				MOV AH,02H 
				MOV DL,0AH 			;SALTO DE LÍNEA
				INT 21H
				MOV AH,02H 
				MOV DL,0DH 			;RETORNO DE CARRO
				INT 21H
				RET
			SALTOLINEA ENDP
			
			;NOTA: (analizar diagrama de flujo)
				;PARA EVITAR UN SALTO REDUNDANTE EN: B MOD D = 0 (FALSO) Y EN: E=2 (FALSO) LO IDEAL ES PONER EL INCREMENTADOR
				;B++ Y D++ ANTES DE LA DECISIÓN, LÍNEAS 14 Y 19 RESPECTIVAMENTE.
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
;EN ESTE CASO B Y D INICIAN EN CERO Y CON EL IMCREMENTADOR ANTES DE LA DECISIÓN TOMAN EL VALOR DE UNO SIN AFECTAR LA LÓGICA DEL PROGRAMA:
A DW 0
B DW 0	;1
D DW 0	;1
E DW 0
F DW 0
;VARIABLES PARA LA UNIÓN DE LOS NÚMEROS.
J DW 10
K DW 100
P DW 1000
;CONTADORES:
N DB 0H				;CUENTA LAS VECES QUE SE HA INGRESADO UN NÚMERO.
I DB 0H				;CONTADOR DE LA SUBRUTINA PARA IMPRIMIR EL RESULTADO EN DECIMAL.
;VARIABLES DONDE SE ALMACENAN RESULTADOS:
M DW 0H				;SE ALMACENA EL VALOR MULTIPLICADO POR 10.
O DW 0H				;SE ALMACENA EL VALOR MULTIPLICADO POR 100.
MENSAJE DB "INGRESE UN NUMERO: $"
DATOS ENDS

END
