ASSUME CS:CODIGO, DS:DATOS, SS:PILA

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX
	
	;OPERACIONES DE LA MULTIPLICACIÓN:
	
		;1)		AX=AL*BL		BYTE POR BYTE, SE ALMACENA EN UN REGISTRO DE 16 BITS (1 PALABRA).
		
		;2)		DX:AX=AX*BX 	PALABRA POR PALABRA, SE ALMACENA EN UN REGISTRO DE 32 BITS (DOBLE PALABRA).
		
	;MULTIPICACIÓN BYTE POR BYTE:
	
	MOV AL, 8
	MOV BL, 230
	MUL BL ;= 730H
	MOV RES, AX
	
	;MULTIPLICACIÓN PALABRA POR PALABRA:
	
	MOV AX, 23690
	MOV BX, 45781
	MUL BX ;= 40A4F2D2H
	;PARA QUE SE PUEDA GUARDAR EL RESULTADO HAY QUE DIVIDIRLO EN SUS DOS PARTES (DX:AX) Y GUARDARLAS POR SEPARADO. POR EL ORDEN
	;QUE TIENEN LAS VARIABLES DE 16 BITS EN EL SEGMENTO DE DATOS, EL RESULTADO SE GUARDA AL REVÉS EN EL VECTOR RES; PERO
	;COMO TAL VECTOR YA TIENE OCUPADO UNA PALABRA Y ES DE TIPO DW TALES PARTES SE GUARDAN DE 2 EN 2.
	MOV RES+2, AX
	MOV RES+4, DX
	
	;MULTIPLICACIÓN PALABRA POR BYTE Y VICEVERSA (HACERLO CON LA OPREACIÓN 2):
	
	MOV AX, 63254
	MOV BX, 41
	MUL BX ;= 279286H
	MOV RES+6, AX
	MOV RES+8, DX
	
	MOV AX, 166
	MOV BX, 23147
	MUL BX ;= 3AA162H
	MOV RES+10, AX
	MOV RES+12, DX
	
	;PROPIEDAD CONMUTATIVA:
	
	;BYTE POR BYTE:
	
	MOV AL, OP1
	MOV BL, OP2
	MUL BL ;= 75CH
	
	MOV AL, OP2
	MOV BL, OP1
	MUL BL ;= 75CH
	
	;PALABRA POR PALABRA:
	
	MOV AX, OP3
	MOV BX, OP4
	MUL BX ;= 2095029EH
	
	MOV AX, OP4
	MOV BX, OP3
	MUL BX ;= 2095029EH
	
	;PALABRA POR BYTE Y VICEVERSA:
	
	MOV AX, OP4
	MOV BX, OP5
	MUL BX ;= 2B08CH
	
	MOV AX, OP5
	MOV BX, OP4
	MUL BX ;= 2B08CH
	
	;MULTIPLICACIÓN BYTE POR BYTE EN REGISTRO AX (HACERLO CON LA OPERACION 2 Y CAMBIAR EL TIPO DE DB A DW):
	
	MOV AX, OP5
	MOV BX, OP6
	MUL BX ;= 0000075CH ;SE ALMACENA EN UN RSGISTRO DE 16 BITS.
	
	;CONCLUSIONES:
	
		;NO SE PUEDE MULTIPLICAR DOS NÚMEROS DE 32 BITS O MAYOR O FUERA DEL RANGO DE 2^16 POR OTRO NUMERO CUALQUIERA
		;NO SE PUEDE MULTIPLICAR 94563*54, PORQUE EL DIVIDENDO ESTÁ POR FUERA DEL RANGO DE LOS 2^16.
		;LA SOLUCIÓN ES ALMACENAR TAL VALOR EN UN REGISTRO EAX DE 32 BITS, PERO EN EL CURSO SÓLO SE UTILIZARÁ HASTA LOS 16 BITS.
		;SI SE UTILIZA UN VECTOR PARA ALMACENAR LOS RESULTADOS DEBE TENERSE EN CUENTA EL TIPO DEL MISMO, SI ES TIPO DW 
		;VA DE 2 EN 2, SI ES DB VA DE 1 EN 1.

	MOV AH,4Ch  
	INT 21h         
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
OP1 DB 12
OP2 DB 157
OP3 DW 37214
OP4 DW 14689
OP5 DW 12
OP6 DW 157
;LOS RESULTADOS DE LOS REGISTROS DE 16 BITS SE GUARDAN EN UN VECTOR DE TIPO DW CON 30 ESPACIOS RESERVADOS EN EL DS(MEDIANTE LA
;INTRUCCIÓN DUP (DUPLICAR):
RES DW 30 DUP(?)
DATOS ENDS

END