ASSUME CS:CODIGO, DS:DATOS, SS:PILA

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX
	
	;OPERACIONES DE LA MULTIPLICACIÓN:
	
		;1)		AX=AL*BL		BYTE POR BYTE, SE ALMACENA EN UN REGITRO DE 16 BITS (1 PALABRA).
		
		;2)		DX:AX=AX*BX 	PALABRA POR PALABRA, SE ALMACENA EN UN REGISTRO DE 32 BITS (DOBLE PALABRA).
		
	;MULTIPICACIÓN BYTE POR BYTE:
	
	MOV AL, 8
	MOV BL, 230
	MUL BL ;= 730H
	
	;MULTIPLICACIÓN PALABRA POR PALABRA:
	
	MOV AX, 23690
	MOV BX, 45781
	MUL BX ;= 40A4F2D2H
	
	;MULTIPLICACIÓN PALABRA POR BYTE Y VICEVERSA (HACERLO CON LA OPREACIÓN 2):
	
	MOV AX, 63254
	MOV BX, 41
	MUL BX ;= 279286H
	
	MOV AX, 166
	MOV BX, 23147
	MUL BX ;= 3AA162
	
	;PROPIEDAD CONMUTATIVA:
	
	;BYTE POR BYTE:
	
	MOV AL, OP1
	MOV BL, OP2
	MUL BL ;= 75CH
	
	MOV AL, OP2
	MOV BL, OP1
	MUL BL ;= 75CH
	
	;PALABRA POR PALABRA:
	
	MOV AX, OP3
	MOV BX, OP4
	MUL BX ;= 2095029EH
	
	MOV AX, OP4
	MOV BX, OP3
	MUL BX ;= 2095029EH
	
	;PALABRA POR BYTE Y VICEVERSA:
	
	MOV AX, OP4
	MOV BX, OP5
	MUL BX ;= 2B08CH
	
	MOV AX, OP5
	MOV BX, OP4
	MUL BX ;= 2B08CH
	
	;MULTIPLICACIÓN BYTE POR BYTE EN REGISTRO AX (HACERLO CON LA OPERACION 2 Y CAMBIAR EL TIPO DE DB A DW):
	
	MOV AX, OP5
	MOV BX, OP6
	MUL BX ;= 0000075CH ;SE ALMACENA EN UN RSGISTRO DE 16 BITS.
	
	;NO SE PUEDE MULTIPLICAR UN NÚMERO MAYOR O FUERA DEL RANGO DE 2^16 POR OTRO NUMERO CUALQUIERA:
	;NO SE PUEDE MULTIPLICAR 94563*54, PORQUE EL DIVIDENDO ESTÁ POR FUERA DEL RANGO DE LOS 2^16.
	;LA SOLUCIÓN ES ALMACENAR TAL VALOR EN UN REGISTRO EAX DE 32 BITS, PERO EN EL CURSO SÓLO SE UTILIZARÁ HASTA LOS 16 BITS.

	MOV AH,4Ch  
	INT 21h         
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
OP1 DB 12
OP2 DB 157
OP3 DW 37214
OP4 DW 14689
OP5 DW 12
OP6 DW 157
DATOS ENDS

END
