ASSUME CS:CODIGO, DS:DATOS, SS:PILA

;REALICE UN PROGRAMA QUE INGRESE POR TECLADO UNA CADENA DE CARACTERES HASTA QUE SE OPRIMA ENTER Y LA MUESTRA EN PANTALLA DE FORMA INVERTIDA CONTADOR
;CON TODAS LAS LETRAS EN MAYÚSCULAS Y ADEMÁS QUE SE VISUALICE CUÁNTAS VECES APARECE CADA VOCAL EN LA CADENA.

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX

ETIQ3:
	MOV AH, 01H
	INT 21H
	MOV AH, 0H
	CMP AL, 0DH
	JE ETIQ1
	CMP AL, a
	JNE ETIQ2
	PUSH AX
	INC D
	INC F
	JMP ETIQ3
ETIQ2:
	CMP AL, e
	JNE ETIQ4
	PUSH AX
	INC D
	INC F
	JMP ETIQ3
ETIQ4:
	CMP AL, i
	JNE ETIQ5
	PUSH AX
	INC D
	INC F
	JMP ETIQ3
ETIQ5:
	CMP AL, o
	JNE ETIQ6
	PUSH AX
	INC D
	INC F
	JMP ETIQ3
ETIQ6:
	CMP AL, u
	JNE ETIQ7
	PUSH AX
	INC D
	INC F
	JMP ETIQ3
ETIQ7:
	PUSH AX
	INC F
	JMP ETIQ3
ETIQ1:				
	CALL SALTOLINEA		;PARA QUE EL RESULTADO NO SE MUESTRE EN LA MISMA LÍNEA DONDE SE INGRESARON LAS LETRAS.
ETIQ8:
	CMP F, 0H
	JE CONTARVOCALES
	POP DX				;SE SACA DE LA PILA LA CANTIDAD DE LETRAS QUE INDICA F.
	SUB DL, 20H			;SE HACE LA CONVERSIÓN DE MINÚSCULAS A MAYÚSCULAS.
	MOV AH, 02H
	INT 21H
	DEC F
	JMP ETIQ8
CONTARVOCALES:
	CALL SALTOLINEA
	MOV AX, D
	CALL IMPRIMIR
FIN:
	MOV AH,4CH  
	INT 21H 
		
		;SUBRUTINA PARA IMPRIMIR EN FORMATO DECIMAL LA CANTIDAD DE VOCALES:
		IMPRIMIR PROC
			MOV BX, 0AH		
		ET2:					;SE HACE LA DIVISIÓN DEL NÚMERO EN B16 QUE ESTÁ EN AX / A.
			CMP AX, 0H			;COMPRUEBA SI EL DIVISOR HA LLEGADO A CERO.
			JE ET3
			MOV DX, 0H			;SE HACE USO DE LA OPERACIÓN 1) EXPLICADA EN EL ARCHIVO DIV.ASM, PARA ESO DX DEBE RELLENARSE DE CEROS.
			DIV BX
			PUSH DX				;SE PONE EL RESIDUO DE LA DIVISIÓN EN LA PILA.
			INC K
			JMP ET2
		ET3:
			CALL SALTOLINEA		
			MOV AH, 09H
			LEA DX, MENSAJE2	;MENSAJE DE SALIDA
			INT 21H
		ET1:
			CMP K, 0H
			JE FIN
			POP DX				;SE SACA DE LA PILA EL RESIDUO QUE SE INGRESO.
			ADD DL, 30H			;SE SUMA 30H AL NÚMERO QUE ESTÁ EN DL PARA HACER LA CONVERSIÓN A ASCII.
			MOV AH, 02H
			INT 21H
			DEC K
			JMP ET1
			RET
		IMPRIMIR ENDP
		
		;SUBRUTINA PARA EL SALTO DE LÍNEA:
			SALTOLINEA PROC
				MOV AH,02H 
				MOV DL,0AH ;SALTO DE LÍNEA
				INT 21H
				MOV AH,02H 
				MOV DL,0DH ;RETORNO DE CARRO
				INT 21H
				RET
			SALTOLINEA ENDP
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
a DB 61H
e DB 65H
i DB 69H
o DB 6FH
u DB 75H
D DW 0H		;LLEVA LA CUENTA DE LA CANTIDAD DE VOCALES QUE SE HAN INGRESADO.
F DW 0H		;LLEVA LA CUENTA DE LA CANTIDAD DE LETRAS QUE SE HAN INGRESADO A LA PILA PARA QUE ESA MISMA CANTIDAD SEA SACADA.
K DB 0H		;CONTADOR DE LA SUBRUTINA PARA IMPRIMIR EL RESULTADO EN DECIMAL.
MENSAJE2 DB "LA CANTIDAD DE VOCALES ES: $"
DATOS ENDS

END
