ASSUME CS:CODIGO, DS:DATOS, SS:PILA

;REALICE UN PROGRAMA QUE SUME DOS NÚMEROS INGRESADOS POR TECLADO, CADA NUMERO PUEDE TENER ENTRE UNO Y CINCO DÍGITOS DECIMALES.

;A TENER EN CUENTA:	*NO SE PUEDE REALIZAR LA SUMA DE DOS NÚMEROS LA CUAL SU RESULTADO SUPEREN EL TOPE DE 65535.
;					*IMPORTANTE REINICIAR EL VALOR DEL CONTADOR N DESPUÉS DE QUE SE HALLA INGRESADO UN NÚMERO.
;					*LA ÚNICA MODIFICACIÓN A LA SUBRUTINA LECTNUM ES EL CONTADOR D.
;					*EL USO DEL CONTADOR D (LÍNEA 146), ES EL QUE DEFINE CADA NÚMERO QUE SE INGRESA.
;					*PONER AH EN CEROS CUANDO SE UTILICE UN SERVICIO (LÍNEA 45).
;					*EL USO DE OTRAS SUBRUTINAS Y SUS RESPECTIVAS VARIABLES EN EL DS.

CODIGO SEGMENT	
	MOV AX,DATOS
	MOV DS,AX
	
	ETIQ7:
	CALL LECTURA_NUMERO 	
	CMP D, 1H			;SI D=1 SU VALOR VA A CORRESPONDER A 'A' EL CUAL ES EL PRIMER NÚMERO DE LA SUMA.
	JNE ETIQ6
	MOV A, AX
	MOV N, 0H			;SE RESETEA EL VALOR DE N PORQUE N LLEVA LA CUENTA DE LA CANTIDAD DE DÍGITOS QUE TIENE UN NÚMERO Y 
	CALL SALTOLINEA			;POR CADA NÚMERO LA CUENTA DEBE DE EMPEZAR EN CERO.
	JMP ETIQ7
ETIQ6:
	CMP D, 2H			;SI D=2 SU VALOR VA A CORRESPONDER A 'B' EL CUAL ES EL SEGUNDO NÚMERO DE LA SUMA.
	JNE FIN
	MOV B, AX
;SUMA DE LOS DOS NÚMEROS INGRESADOS:
	MOV AX, A
	ADD AX, B			;EL RESULTADO QUEDA ALMACENADO EN AX LISTO PARA SER IMPRIMIDO EN PANTALLA.
	CALL IMPRIMIR_DECIMAL
FIN:
	MOV AH, 4CH
	INT 21H
	
			;SUBRUTINA PARA EL INGRESO POR TECLADO DE UN NÚMERO DE 5 DÍGITOS: (revisar archivo LECTNUM.ASM)
			LECTURA_NUMERO PROC
				;BREVE MENSAJE:
				MOV AH, 09H
				LEA DX, MENSAJE
				INT 21H
				;INGRESO DE LOS DÍGITOS DEL NÚMERO:
			LECTNUM2:
				MOV AH, 01H
				INT 21H
				MOV AH, 0H			;PARA QUE QUE NO INTERFIERA EL SERVICIO 01H EN EL REGISTRO AX.
				CMP AL, 0DH			;EL INGRESO DE DÍGITOS TERMINA CUANDO SE HALLA PRESIONADO LA TECLA ENTER O 
				JE LECTNUM1				;SE HALLA LLEGADO AL TOPE, EL CUAL ES UN NÚMERO DE 5 DÍGITOS.
				PUSH AX
				INC N				;N ES UN CONTADOR QUE LLEVA LA CUENTA DE LOS DÍGITOS QUE SE HAN INGRESADO A 
				CMP N, 5H				;LA PILA, ADEMÁS DETERMINA EL TIPO DE NÚMERO A PARTIR DE SUS DÍGITOS. SI N=5, QUIERE 
				JE LECTNUM1				;DECIR QUE SE HA LLEGADO AL TOPE Y SE HA INGRESADO UN NÚMERO DE 5 DÍGITOS.
				JMP LECTNUM2
				;DETERMINACIÓN DEL NÚMERO INGRESADO A PARTIR DE SUS DÍGITOS:
			LECTNUM1:
				CMP N, 01H 			;PARA UN NÚMERO DE UN DÍGITO.
				JNE LECTNUM3
				POP AX
				SUB AX, 30H			;CONVERSIÓN DE ASCCI A DECIMAL.
				JMP SALIR			;RESULTADO GUARDADO EN AX.
			LECTNUM3:
				CMP N, 02H			;PARA UN NÚMERO DE DOS DÍGITOS.
				JNE LECTNUM4
				POP AX
				SUB AX, 30H
				MOV BX, AX			;BX GUARDA EL DÍGITO DOS.
				POP AX
				SUB AX, 30H
				MOV CX, J
				MUL CX				;MULTIPLICA EL DÍGITO UNO POR 10^1 Y EL RESULTADO SE GUARDA EN DX/AX.
				ADD AX, BX			;SE SUMAN EL DÍGITO UNO CON EL DOS Y EL RESULTADO SE GUARDA EN AX.
				JMP SALIR
			LECTNUM4:
				CMP N, 03H			;PARA UN NÚMERO DE TRES DÍGITOS.
				JNE LECTNUM5
				POP AX
				SUB AX, 30H
				MOV BX, AX			;BX GUARDA EL DÍGITO TRES.
				POP AX
				SUB AX, 30H
				MOV CX, J
				MUL CX				;AX GUARDA EL DÍGITO DOS.	
				ADD AX, BX
				MOV R, AX			;LA SUMA DEL DÍGITO DOS CON EL TRES SE GUARDA EN R.
				POP AX
				SUB AX, 30H
				MOV CX, K
				MUL CX				;MULTIPLICA EL DÍGITO UNO POR 10^2 Y EL RESULTADO SE GUARDA EN DX/AX.
				ADD AX, R			;AX = AX+(R+BX).
				JMP SALIR			;SE SUMAN LOS TRES DÍGITOS Y EL RESULTADO SE GUARDA EN AX.
			LECTNUM5:
				CMP N, 04H			;PARA UN NÚMERO DE CUATRO DÍGITOS.
				JNE LECTNUM6
				POP AX
				SUB AX, 30H
				MOV BX, AX			;BX GUARDA EL DÍGITO TRES.
				POP AX
				SUB AX, 30H
				MOV CX, J
				MUL CX				;AX GUARDA EL DÍGITO DOS.	
				ADD AX, BX
				MOV R, AX			;LA SUMA DEL DÍGITO DOS CON EL TRES SE GUARDA EN R.
				POP AX
				SUB AX, 30H
				MOV CX, K
				MUL CX				
				ADD AX, R
				MOV S, AX			;LA SUMA DEL DÍGITO TRES, DOS Y UNO SE GUARDA EN S.
				POP AX
				SUB AX, 30H
				MOV CX, P
				MUL CX				;MULTIPLICA EL DÍGITO UNO POR 10^3 Y EL RESULTADO SE GUARDA EN DX/AX.
				ADD AX, S 			;AX = AX+(S+(R+BX)).
				JMP SALIR			;SE SUMAN LOS CUATRO DÍGITOS Y EL RESULTADO SE GUARDA EN AX.
			LECTNUM6:
				CMP N, 05H			;PARA UN NÚMERO DE CINCO DÍGITOS.
				JNE SALIR
				POP AX
				SUB AX, 30H
				MOV BX, AX			;BX GUARDA EL DÍGITO TRES.
				POP AX
				SUB AX, 30H
				MOV CX, J
				MUL CX				;AX GUARDA EL DÍGITO DOS.	
				ADD AX, BX
				MOV R, AX			;LA SUMA DEL DÍGITO DOS CON EL TRES SE GUARDA EN R.
				POP AX
				SUB AX, 30H
				MOV CX, K
				MUL CX				
				ADD AX, R
				MOV S, AX			;LA SUMA DEL DÍGITO TRES, DOS Y UNO SE GUARDA EN S.
				POP AX
				SUB AX, 30H
				MOV CX, P
				MUL CX
				ADD AX, S
				MOV T, AX			;LA SUMA DEL DÍGITO CUATRO, TRES, DOS Y UNO SE GUARDA EN T.
				POP AX
				SUB AX, 30H
				MOV CX, O
				MUL CX				;MULTIPLICA EL DÍGITO UNO POR 10^4 Y EL RESULTADO SE GUARDA EN DX/AX.
				ADD AX, T			;AX = AX+(T+(S+(R+BX))).
				JMP SALIR			;SE SUMAN LOS CUATRO DÍGITOS Y EL RESULTADO SE GUARDA EN AX.
			SALIR:
				INC D				;D LLEVA LA CUENTA POR CADA NÚMERO QUE SE INGRESE.
				RET
			LECTURA_NUMERO ENDP

			SALTOLINEA PROC
				MOV AH,02H 
				MOV DL,0AH 			;SALTO DE LÍNEA
				INT 21H
				MOV AH,02H 
				MOV DL,0DH 			;RETORNO DE CARRO
				INT 21H
				RET
			SALTOLINEA ENDP
			
			IMPRIMIR_DECIMAL PROC
				MOV BX, 0AH		;EN BX SE ALMACENA EL DIVISOR A.
			IMPDECI2:
				CMP AX, 0H		;COMPRUEBA SI EL DIVISOR HA LLEGADO A CERO, SI ES CERO ENTONCES SALTA A IMPRIMIR.
				JE IMPDECI1
				MOV DX, 0H		;SE HACE USO DE LA OPERACIÓN AX=DX:AX/OP, PARA ESO DX DEBE RELLENARSE DE CEROS.
				DIV BX
				PUSH DX			;SE PONE EL RESIDUO DE LA DIVISIÓN EN LA PILA.
				INC I
				JMP IMPDECI2
			IMPDECI1:
				CALL SALTOLINEA
				LEA DX, MENSAJE2
				MOV AH, 09H
				INT 21H
			IMPDECI3:
				CMP I, 0H
				JE FIN_IMPRIMIR
				POP DX			;SE SACA DE LA PILA EL RESIDUO QUE SE INGRESÓ.
				ADD DX, 30H		;SE SUMA 30H PARA HACER LA CONVERSIÓN DE DECIMAL A ASCII.
				MOV AH, 02H
				INT 21H
				DEC I
				JMP IMPDECI3
			FIN_IMPRIMIR:
				RET
			IMPRIMIR_DECIMAL ENDP
	
CODIGO ENDS

PILA SEGMENT STACK
	DW 32 DUP (0)
PILA ENDS

DATOS SEGMENT
;POTENCIAS DE 10:
J DW 10
K DW 100
P DW 1000
O DW 10000
;CONTADORES DEL PROGRAMA:
N DB 0H							;DETERMINA EL TIPO DE NÚMERO A PARTIR DE SUS DÍGITOS.
I DW 0H							;CONTADOR DE LA SUBRUTINA IMPRIMIR_DECIMAL.
D DW 0H							;D ES EL CONTADOR QUE LLEVA LA CUENTA DE LAS VECES QUE SE HAN INGRESADO LOS NÚMEROS PARA SER SUMADOS. EN ESTE CASO EL VALOR 
									;MÁXIMO DE D ES 2 YA QUE SE DEBEN DE SUMAR DOS NÚMEROS.
;VARIABLES QUE GUARDAN VALORES:
R DW 0H
S DW 0H
T DW 0H
A DW 0H							;GUARDA EL RESULTADO DEL PRIMER NÚMERO INGRESADO.
B DW 0H							;GUARDA EL RESULTADO DEL SEGUNDO NÚMERO INGRESADO.
;MENSAJES:
MENSAJE DB "INGRESE NUMERO: $"
MENSAJE2 DB "LA SUMA ES: $"
DATOS ENDS

END
